/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programas;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hdavi
 */
public class venJuego extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    public venJuego() {
        initComponents();
         jLabel7.setVisible(false);
        
        
        jLabel9.addMouseListener(new MouseAdapter() {
	    public void mouseClicked(MouseEvent e) { 
       
                
                jLabel7.setVisible(true);

                int numero = 1 + (int) (Math.random() * 6);
                String nDado = Integer.toString(numero);
                ImageIcon dado  = new ImageIcon("src/img/"+nDado+".png");
                Icon caraDado = new ImageIcon(dado.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
                jLabel6.setIcon(caraDado);
                //jLabel6.repaint();
                
                
                
                
                switch (turno) {

                case 1:
                    
                    jLabel7.setBackground(new Color(255, 0, 0));
                    //jLabel8.setLocation(120, 43);
                    turno++;
                    
                    break;
                case 2:
                    jLabel7.setBackground(new Color(66, 1, 76));
                    //jLabel8.setLocation(120, 98);
                    turno++;
                    break;
                case 3:
                    jLabel7.setBackground(new Color(255, 240, 0));
                    //jLabel8.setLocation(120, 153);
                    turno++;
                    break;
                case 4:
                    jLabel7.setBackground(new Color( 0, 255, 252));
                    //jLabel8.setLocation(120, 212);
                    turno = 1;
                    break;

                }
	    	
	  
	    }  
	});
        
        ImageIcon imagenF  = new ImageIcon("src/img/tableroFinal.png");
        Icon icono = new ImageIcon(imagenF.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        this.repaint();
        
        
       
        
        ImageIcon dado  = new ImageIcon("src/img/6.png");
        Icon caraDado = new ImageIcon(dado.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_DEFAULT));
        jLabel6.setIcon(caraDado);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escaleras Y Serpientes");
        setResizable(false);
        setSize(new java.awt.Dimension(730, 704));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 255, 252));
        jLabel2.setText("Jugador 4");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 212, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 240, 0));
        jLabel3.setText("Jugador 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 153, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 5, 0));
        jLabel4.setText("Jugador 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 43, -1, -1));

        jLabel5.setForeground(new java.awt.Color(66, 1, 76));
        jLabel5.setText("Jugador 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 98, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, 180));

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 176, 250));

        jLabel9.setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 171, 40));

        jLabel1.setName("fondo"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 704));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venJuego().setVisible(true);
            }
        });
    }

    public int turno = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
